### ISSUE TITLE
Trying to accelerate turtlebot3 node following acceleration example

### ISSUE THREAD

**Issue by mvgianel** [ros-acceleration/acceleration_examples#21]
I am trying to build the turtlebot3 nodes on the kria by following [this ](https://xilinx.github.io/KRS/sphinx/build/html/docs/examples/1_hello_xilinx.html)tutorial. However, when I try to build the turtlebot3 node package fot the KV260, I get this error:

![image](https://user-images.githubusercontent.com/23347523/216430177-e02376a4-b74f-4ebf-8ad5-fba8842f9b3a.png)

Does someone know what could be causing this?

**Comment by vmayoral** [comment]
Clearly, you're missing `libpython3.9.so`. 

Note also:
- the tutorial you linked is part of AMD solutions however this repo is community-centric and driven. Things might differ depending on what you're trying to do.
- `turtlebot3_node` is not a package that's in this repository, so I don't quite understand why you're asking support in here, or if that package has "special" needs we did not consider in here. In any case that's beyond the scope of this repository.
