### ISSUE TITLE
Failed to launch hello_xilinx in an emulated KV260 

### ISSUE THREAD

**Issue by surender009** [ros-acceleration/acceleration_examples#3]
surender@xhdsurender41:/scratch/KRS/krs_ws$ colcon acceleration emulation sw_emu install-kv260
SECURITY WARNING: This class invokes explicitly a shell via the shell=True argument of the Python subprocess library, and uses admin privileges to manage raw disk images. It is the user's responsibility to ensure that all whitespace and metacharacters passed are quoted appropriately to avoid shell injection vulnerabilities.
- Verified that install/ is available in the current ROS 2 workspace
- Confirmed availability of raw image file at: /scratch/KRS/krs_ws/acceleration/firmware/select/sd_card.img
- Finished inspecting raw image, obtained UNITS and STARTSECTOR P1/P2
- Image mounted successfully at: /tmp/sdcard_img_p2
- Successfully cleaned up prior overlay ROS 2 workspace at: /tmp/sdcard_img_p2/ros2_ws
- Copied 'install-kv260' directory as a ROS 2 overlay workspace in the raw image.
- Umounted the raw image.
- Generated PMU and QEMU files.
- Launching emulation...
cd /scratch/KRS/krs_ws/acceleration/firmware/select/emulation && /proj/xbuilds/SWIP/2020.2_1118_1232/installs/lin64/Vitis/2020.2/bin/launch_emulator -device-family ultrascale -target sw_emu -qemu-args-file /scratch/KRS/krs_ws/acceleration/firmware/select/emulation/qemu_args.txt -pmc-args-file /scratch/KRS/krs_ws/acceleration/firmware/select/emulation/pmu_args.txt -sd-card-image /scratch/KRS/krs_ws/acceleration/firmware/select/sd_card.img -enable-prep-target $*
Running SW Emulation
INFO :  [LAUNCH_EMULATOR] pl_sim_dir option is not provided.
Starting QEMU
 - Press <Ctrl-a h> for help
Waiting for QEMU to start. qemu_port 7376
Qemu_pids 1045781 1045782
qemu-system-aarch64: -chardev socket,path=./qemu-rport-_pmu@0,server,id=pmu-apu-rp: info: QEMU waiting for connection on: disconnected:unix:./qemu-rport-_pmu@0,server
QEMU started. qemu_pid=1045781.
Waiting for PMU to start. Qemu_pids 1045801 1045802
qemu-system-aarch64: -chardev socket,id=pl-rp,host=127.0.0.1,port=9248,server: info: QEMU waiting for connection on: disconnected:tcp:127.0.0.1:9248,server
PMC started. pmc_pid=1045801
Starting PL simulation.Generating PLLauncher commandline
running PLL Launcher
qemu-system-aarch64: Could not reopen file: Permission denied
qemu-system-microblazeel: /pmu@0: Disconnected clk=5263364164 ns

[LAUNCH_EMULATOR] INFO: 13:00:55 : PS-QEMU exited
[LAUNCH_EMULATOR] INFO: 13:00:57 : PS-QEMU exited
[LAUNCH_EMULATOR] INFO: 13:00:57 : PMU/PMC-QEMU exited
[LAUNCH_EMULATOR] INFO: 13:00:57 : Trying to kill PLLauncher forcefully because QEMU exited
[LAUNCH_EMULATOR] INFO: 13:00:57 : PLLauncher exited by force
Please refer PS /simulate logs at /scratch/KRS/krs_ws/acceleration/firmware/kv260/emulation for more details.
DONE!
INFO: Emulation ran successfully
Finalized successfully.

**Comment by vmayoral** [comment]
@surender009 this seems connected to https://github.com/ros-acceleration/acceleration_examples/issues/3. Can you please check that and if so, resolve this ticket? Let's concentrate the discussion in a single thread.

**Comment by vmayoral** [comment]
Closing since there're not further responses or comments.
